import Foundation

/// A curated collection of short quotes (each under 15 words) from well-known
/// public figures. Rotated on Today at a fixed interval. Extend this array
/// freely — the code makes no assumptions about length.
enum QuoteBank {
    struct Quote: Identifiable, Hashable {
        var id: String { text }
        let text: String
        let author: String
    }

    /// How often the quote on Today changes by itself.
    static let rotationMinutes = 30

    /// Deterministic quote for a given time bucket — same bucket returns the
    /// same quote, so the UI is stable between renders. Walks the list with a
    /// step that is coprime to its length, so every quote appears once per
    /// cycle in a shuffled-looking order and the same one never repeats back
    /// to back.
    static func quote(at date: Date = .now, bucketMinutes: Int = rotationMinutes) -> Quote {
        let bucket = Int(date.timeIntervalSince1970) / (bucketMinutes * 60)
        return all[(abs(bucket) * step) % all.count]
    }

    /// Seconds until the current quote rotates out.
    static func secondsUntilNext(from date: Date = .now, bucketMinutes: Int = rotationMinutes) -> TimeInterval {
        let length = Double(bucketMinutes * 60)
        let t = date.timeIntervalSince1970
        return length - t.truncatingRemainder(dividingBy: length)
    }

    private static let step: Int = {
        func gcd(_ a: Int, _ b: Int) -> Int { b == 0 ? a : gcd(b, a % b) }
        var s = max(1, all.count * 5 / 8)
        while gcd(s, all.count) != 1 { s += 1 }
        return s
    }()

    static let all: [Quote] = [
        .init(text: "The only way to do great work is to love what you do.", author: "Steve Jobs"),
        .init(text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein"),
        .init(text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu"),
        .init(text: "What you do every day matters more than what you do once in a while.", author: "Gretchen Rubin"),
        .init(text: "Discipline equals freedom.", author: "Jocko Willink"),
        .init(text: "Fall seven times, stand up eight.", author: "Japanese proverb"),
        .init(text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: "Chinese proverb"),
        .init(text: "Little by little, one travels far.", author: "J.R.R. Tolkien"),
        .init(text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt"),
        .init(text: "The obstacle is the way.", author: "Marcus Aurelius"),
        .init(text: "You have power over your mind, not outside events.", author: "Marcus Aurelius"),
        .init(text: "Waste no more time arguing what a good person should be. Be one.", author: "Marcus Aurelius"),
        .init(text: "We suffer more in imagination than in reality.", author: "Seneca"),
        .init(text: "While we wait for life, life passes.", author: "Seneca"),
        .init(text: "Every new beginning comes from some other beginning's end.", author: "Seneca"),
        .init(text: "First say to yourself what you would be; then do what you have to do.", author: "Epictetus"),
        .init(text: "It's not what happens to you, but how you react that matters.", author: "Epictetus"),
        .init(text: "No man is free who is not master of himself.", author: "Epictetus"),
        .init(text: "The mind is everything. What you think, you become.", author: "Buddha"),
        .init(text: "You yourself, as much as anybody, deserve your love and affection.", author: "Buddha"),
        .init(text: "Peace comes from within. Do not seek it without.", author: "Buddha"),
        .init(text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein"),
        .init(text: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein"),
        .init(text: "Imagination is more important than knowledge.", author: "Albert Einstein"),
        .init(text: "Life is like riding a bicycle. To keep balance, you must keep moving.", author: "Albert Einstein"),
        .init(text: "Stay hungry. Stay foolish.", author: "Stewart Brand"),
        .init(text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs"),
        .init(text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci"),
        .init(text: "Learning never exhausts the mind.", author: "Leonardo da Vinci"),
        .init(text: "It always seems impossible until it's done.", author: "Nelson Mandela"),
        .init(text: "There is no passion in playing small.", author: "Nelson Mandela"),
        .init(text: "Education is the most powerful weapon to change the world.", author: "Nelson Mandela"),
        .init(text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi"),
        .init(text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi"),
        .init(text: "Strength does not come from physical capacity. It comes from indomitable will.", author: "Mahatma Gandhi"),
        .init(text: "The future depends on what you do today.", author: "Mahatma Gandhi"),
        .init(text: "Do not go where the path may lead; go where there is no path.", author: "Ralph Waldo Emerson"),
        .init(text: "What lies behind us is tiny compared to what lies within us.", author: "Ralph Waldo Emerson"),
        .init(text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson"),
        .init(text: "The only person you are destined to become is who you decide to be.", author: "Ralph Waldo Emerson"),
        .init(text: "Success is not final, failure is not fatal.", author: "Winston Churchill"),
        .init(text: "If you're going through hell, keep going.", author: "Winston Churchill"),
        .init(text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill"),
        .init(text: "Never, never, never give up.", author: "Winston Churchill"),
        .init(text: "The best way to predict the future is to create it.", author: "Peter Drucker"),
        .init(text: "What gets measured gets managed.", author: "Peter Drucker"),
        .init(text: "Efficiency is doing things right. Effectiveness is doing the right things.", author: "Peter Drucker"),
        .init(text: "Well done is better than well said.", author: "Benjamin Franklin"),
        .init(text: "Lost time is never found again.", author: "Benjamin Franklin"),
        .init(text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin"),
        .init(text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin"),
        .init(text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin"),
        .init(text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
        .init(text: "Nothing worth having comes easy.", author: "Theodore Roosevelt"),
        .init(text: "Comparison is the thief of joy.", author: "Theodore Roosevelt"),
        .init(text: "In any moment of decision, the best thing is the right thing.", author: "Theodore Roosevelt"),
        .init(text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill"),
        .init(text: "Whether you think you can or can't — you're right.", author: "Henry Ford"),
        .init(text: "Nothing is particularly hard if you divide it into small jobs.", author: "Henry Ford"),
        .init(text: "Failure is simply the opportunity to begin again, more intelligently.", author: "Henry Ford"),
        .init(text: "Quality means doing it right when no one is looking.", author: "Henry Ford"),
        .init(text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney"),
        .init(text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney"),
        .init(text: "It's kind of fun to do the impossible.", author: "Walt Disney"),
        .init(text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky"),
        .init(text: "It's not the years in your life, it's the life in your years.", author: "Abraham Lincoln"),
        .init(text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln"),
        .init(text: "Give me six hours to chop a tree and I'll spend four sharpening the axe.", author: "Abraham Lincoln"),
        .init(text: "The best way out is always through.", author: "Robert Frost"),
        .init(text: "Two roads diverged in a wood, and I took the one less traveled.", author: "Robert Frost"),
        .init(text: "In three words I can sum up everything about life: it goes on.", author: "Robert Frost"),
        .init(text: "If you can dream it, you can do it.", author: "Walt Disney"),
        .init(text: "Act as if what you do makes a difference. It does.", author: "William James"),
        .init(text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James"),
        .init(text: "We are what we repeatedly do. Excellence, then, is a habit.", author: "Will Durant"),
        .init(text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle"),
        .init(text: "Happiness depends upon ourselves.", author: "Aristotle"),
        .init(text: "The whole is greater than the sum of its parts.", author: "Aristotle"),
        .init(text: "Pleasure in the job puts perfection in the work.", author: "Aristotle"),
        .init(text: "Wonder is the beginning of wisdom.", author: "Socrates"),
        .init(text: "The unexamined life is not worth living.", author: "Socrates"),
        .init(text: "He who is not contented with what he has would not be contented with more.", author: "Socrates"),
        .init(text: "An unexamined life is not worth living.", author: "Socrates"),
        .init(text: "I know that I know nothing.", author: "Socrates"),
        .init(text: "Nothing can dim the light which shines from within.", author: "Maya Angelou"),
        .init(text: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou"),
        .init(text: "You will face many defeats, but never be defeated.", author: "Maya Angelou"),
        .init(text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou"),
        .init(text: "Do the best you can until you know better. Then do better.", author: "Maya Angelou"),
        .init(text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy"),
        .init(text: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy"),
        .init(text: "Where there is love there is life.", author: "Mahatma Gandhi"),
        .init(text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi"),
        .init(text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi"),
        .init(text: "The best revenge is massive success.", author: "Frank Sinatra"),
        .init(text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch"),
        .init(text: "What we achieve inwardly will change outer reality.", author: "Plutarch"),
        .init(text: "Character is destiny.", author: "Heraclitus"),
        .init(text: "No man ever steps in the same river twice.", author: "Heraclitus"),
        .init(text: "The only constant in life is change.", author: "Heraclitus"),
        .init(text: "Big shots are only little shots who keep shooting.", author: "Christopher Morley"),
        .init(text: "The expert in anything was once a beginner.", author: "Helen Hayes"),
        .init(text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John Shedd"),
        .init(text: "The purpose of our lives is to be happy.", author: "Dalai Lama"),
        .init(text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama"),
        .init(text: "If you think you are too small to make a difference, try sleeping with a mosquito.", author: "Dalai Lama"),
        .init(text: "Silence is sometimes the best answer.", author: "Dalai Lama"),
        .init(text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden"),
        .init(text: "It's what you learn after you know it all that counts.", author: "John Wooden"),
        .init(text: "Make each day your masterpiece.", author: "John Wooden"),
        .init(text: "Be quick, but don't hurry.", author: "John Wooden"),
        .init(text: "Excellence is never an accident.", author: "Aristotle"),
        .init(text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry"),
        .init(text: "Perfection is achieved not when there is nothing more to add.", author: "Antoine de Saint-Exupéry"),
        .init(text: "The essential is invisible to the eye.", author: "Antoine de Saint-Exupéry"),
        .init(text: "Winners never quit and quitters never win.", author: "Vince Lombardi"),
        .init(text: "The difference between a successful person and others is a lack of strength, not knowledge.", author: "Vince Lombardi"),
        .init(text: "The price of success is hard work and dedication.", author: "Vince Lombardi"),
        .init(text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon"),
        .init(text: "Talent is cheaper than table salt.", author: "Stephen King"),
        .init(text: "Amateurs sit and wait for inspiration. The rest of us just get up and go to work.", author: "Stephen King"),
        .init(text: "Books are uniquely portable magic.", author: "Stephen King"),
        .init(text: "The scariest moment is always just before you start.", author: "Stephen King"),
        .init(text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"),
        .init(text: "The secret of getting ahead is getting started.", author: "Mark Twain"),
        .init(text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain"),
        .init(text: "Twenty years from now you will be more disappointed by the things you didn't do.", author: "Mark Twain"),
        .init(text: "Kind words can be short and easy to speak, but their echoes are endless.", author: "Mother Teresa"),
        .init(text: "Not all of us can do great things. But we can do small things with great love.", author: "Mother Teresa"),
        .init(text: "Peace begins with a smile.", author: "Mother Teresa"),
        .init(text: "If you want to change the world, go home and love your family.", author: "Mother Teresa"),
        .init(text: "Yesterday is history. Tomorrow is a mystery. Today is a gift.", author: "Eleanor Roosevelt"),
        .init(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
        .init(text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt"),
        .init(text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt"),
        .init(text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt"),
        .init(text: "It takes as much energy to wish as it does to plan.", author: "Eleanor Roosevelt"),
        .init(text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein"),
        .init(text: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein"),
        .init(text: "Once you stop learning, you start dying.", author: "Albert Einstein"),
        .init(text: "The important thing is not to stop questioning.", author: "Albert Einstein"),
        .init(text: "Everybody is a genius. But if you judge a fish by its ability to climb, it will live thinking it is stupid.", author: "Albert Einstein"),
        .init(text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison"),
        .init(text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison"),
        .init(text: "Our greatest weakness lies in giving up.", author: "Thomas Edison"),
        .init(text: "There is no substitute for hard work.", author: "Thomas Edison"),
        .init(text: "If we all did the things we are capable of, we would astound ourselves.", author: "Thomas Edison"),
        .init(text: "You can't cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore"),
        .init(text: "Faith is the bird that feels the light when the dawn is still dark.", author: "Rabindranath Tagore"),
        .init(text: "The highest education is that which does not merely give us information but makes our life in harmony with all existence.", author: "Rabindranath Tagore"),
        .init(text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison"),
        .init(text: "A reader lives a thousand lives before he dies.", author: "George R.R. Martin"),
        .init(text: "Today a reader, tomorrow a leader.", author: "Margaret Fuller"),
        .init(text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth"),
        .init(text: "It's hard to beat a person who never gives up.", author: "Babe Ruth"),
        .init(text: "Yesterday's home runs don't win today's games.", author: "Babe Ruth"),
        .init(text: "The way I see it, if you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton"),
        .init(text: "Find out who you are and do it on purpose.", author: "Dolly Parton"),
        .init(text: "Don't get so busy making a living that you forget to make a life.", author: "Dolly Parton"),
        .init(text: "Whatever you are, be a good one.", author: "Abraham Lincoln"),
        .init(text: "Most folks are as happy as they make up their minds to be.", author: "Abraham Lincoln"),
        .init(text: "Am I not destroying my enemies when I make friends of them?", author: "Abraham Lincoln"),
        .init(text: "The best way to escape from a problem is to solve it.", author: "Alan Saporta"),
        .init(text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall"),
        .init(text: "Only put off until tomorrow what you are willing to die having left undone.", author: "Pablo Picasso"),
        .init(text: "Action is the foundational key to all success.", author: "Pablo Picasso"),
        .init(text: "Learn the rules like a pro, so you can break them like an artist.", author: "Pablo Picasso"),
        .init(text: "Everything you can imagine is real.", author: "Pablo Picasso"),
        .init(text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito"),
        .init(text: "Great things never come from comfort zones.", author: "Neil Strauss"),
        .init(text: "Push yourself, because no one else is going to do it for you.", author: "Anonymous"),
        .init(text: "Sometimes later becomes never. Do it now.", author: "Anonymous"),
        .init(text: "Dream bigger. Do bigger.", author: "Anonymous"),
        .init(text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson"),
        .init(text: "Wake up with determination. Go to bed with satisfaction.", author: "George Lorimer"),
        .init(text: "It's going to be hard, but hard does not mean impossible.", author: "Anonymous"),
        .init(text: "Don't stop when you're tired. Stop when you're done.", author: "David Goggins"),
        .init(text: "Wake up and be awesome.", author: "Anonymous"),
        .init(text: "Little things make big days.", author: "Anonymous"),
        .init(text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy"),
        .init(text: "The greatest teacher, failure is.", author: "Yoda"),
        .init(text: "Do or do not. There is no try.", author: "Yoda"),
        .init(text: "Focus on where you want to go, not on what you fear.", author: "Anthony Robbins"),
        .init(text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins"),
        .init(text: "The only impossible journey is the one you never begin.", author: "Tony Robbins"),
        .init(text: "Success is doing ordinary things extraordinarily well.", author: "Jim Rohn"),
        .init(text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn"),
        .init(text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn"),
        .init(text: "You can't hire someone else to do your push-ups for you.", author: "Jim Rohn"),
        .init(text: "Motivation gets you started. Habit keeps you going.", author: "Jim Rohn"),
        .init(text: "For every disciplined effort there is a multiple reward.", author: "Jim Rohn"),
        .init(text: "Time is more valuable than money. You can get more money, but you cannot get more time.", author: "Jim Rohn"),
        .init(text: "If you really want to do something, you'll find a way. If not, you'll find an excuse.", author: "Jim Rohn"),
        .init(text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier"),
        .init(text: "The starting point of all achievement is desire.", author: "Napoleon Hill"),
        .init(text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill"),
        .init(text: "Whatever the mind can conceive and believe, it can achieve.", author: "Napoleon Hill"),
        .init(text: "You are never too old to set another goal or dream a new dream.", author: "C.S. Lewis"),
        .init(text: "Isn't it funny how day by day nothing changes, but when you look back everything is different.", author: "C.S. Lewis"),
        .init(text: "Integrity is doing the right thing, even when no one is watching.", author: "C.S. Lewis"),
        .init(text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis"),
        .init(text: "The clearer you are about what you want, the more likely you are to achieve it.", author: "Brian Tracy"),
        .init(text: "You cannot control what happens to you, but you can control your attitude.", author: "Brian Tracy"),
        .init(text: "The key to success is to focus our conscious mind on things we desire.", author: "Brian Tracy"),
        .init(text: "Eat that frog first thing in the morning.", author: "Brian Tracy"),
        .init(text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss"),
        .init(text: "Being busy is a form of laziness — lazy thinking and indiscriminate action.", author: "Tim Ferriss"),
        .init(text: "Focus on being productive instead of busy.", author: "Tim Ferriss"),
        .init(text: "A person's success in life can usually be measured by the number of uncomfortable conversations they're willing to have.", author: "Tim Ferriss"),
        .init(text: "The quality of your life is directly related to the quality of your questions.", author: "Tim Ferriss"),
        .init(text: "Study while others are sleeping; work while others are loafing.", author: "William Arthur Ward"),
        .init(text: "Do more than belong: participate.", author: "William Arthur Ward"),
        .init(text: "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.", author: "William Arthur Ward"),
        .init(text: "Opportunities don't happen. You create them.", author: "Chris Grosser"),
        .init(text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller"),
        .init(text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis"),
        .init(text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau"),
        .init(text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau"),
        .init(text: "Not until we are lost do we begin to understand ourselves.", author: "Henry David Thoreau"),
        .init(text: "The price of anything is the amount of life you exchange for it.", author: "Henry David Thoreau"),
        .init(text: "How vain it is to sit down to write when you have not stood up to live.", author: "Henry David Thoreau"),
        .init(text: "If we did all the things we are capable of, we would literally astound ourselves.", author: "Thomas Edison"),
        .init(text: "We are what we repeatedly do.", author: "Will Durant"),
        .init(text: "Habits are the compound interest of self-improvement.", author: "James Clear"),
        .init(text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear"),
        .init(text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn"),
        .init(text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier"),
        .init(text: "How we spend our days is, of course, how we spend our lives.", author: "Annie Dillard"),
        .init(text: "Energy and persistence conquer all things.", author: "Benjamin Franklin"),
        .init(text: "Knowing is not enough; we must apply.", author: "Johann Wolfgang von Goethe"),
        .init(text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus"),
        .init(text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca"),
        .init(text: "Our life is what our thoughts make it.", author: "Marcus Aurelius"),
        .init(text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
    ]
}
